#!/usr/bin/env python3
"""Generate the Lua-embedded lobby protobuf descriptor."""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path


CHUNK_SIZE = 128


def render_module(data: bytes, source_label: str) -> str:
    digest = hashlib.sha256(data).hexdigest().upper()
    lines = [
        "-- Generated by tools/generate_lobby_service_pb.py; do not edit.",
        f"-- Source: {source_label}",
        f"-- SHA-256: {digest}",
        "local content = table.concat({",
    ]
    for start in range(0, len(data), CHUNK_SIZE):
        chunk = data[start : start + CHUNK_SIZE]
        escaped = "".join(f"\\x{byte:02X}" for byte in chunk)
        lines.append(f"    '{escaped}',")
    lines.extend(
        [
            "})",
            "",
            f"assert(#content == {len(data)}, 'embedded lobby protocol length mismatch')",
            "return content",
            "",
        ]
    )
    return "\n".join(lines)


def resolve_path(repo_root: Path, value: str) -> Path:
    path = Path(value)
    return path if path.is_absolute() else repo_root / path


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--source",
        default="game/lobby/proto/service.pb",
        help="protobuf descriptor path, relative to the y3-lualib root",
    )
    parser.add_argument(
        "--output",
        default="game/lobby/proto/service_pb.lua",
        help="generated Lua module path, relative to the y3-lualib root",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the generated module is missing or stale",
    )
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[1]
    source = resolve_path(repo_root, args.source)
    output = resolve_path(repo_root, args.output)
    try:
        source_label = source.relative_to(repo_root).as_posix()
    except ValueError:
        source_label = source.name
    expected = render_module(source.read_bytes(), source_label)

    if args.check:
        actual = output.read_text(encoding="ascii") if output.is_file() else None
        if actual != expected:
            print(f"stale generated file: {output}", file=sys.stderr)
            return 1
        print(f"generated file is current: {output}")
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", encoding="ascii", newline="\n") as file:
        file.write(expected)
    print(f"generated: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
